# Generated by Django 5.0.7 on 2024-07-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "alert_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("transaction_time", models.DateTimeField()),
                ("transaction_date", models.DateField()),
                ("exception_level", models.CharField(max_length=100)),
                ("equal_initial_decom_user", models.CharField(max_length=100)),
                ("return_code", models.CharField(max_length=100)),
                ("process_id", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=100)),
                ("batch_id_readed", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("client_id", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("return_code_description", models.CharField(max_length=100)),
                ("process_name", models.CharField(max_length=100)),
                ("mah_id", models.CharField(max_length=100)),
                ("mah_name", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("nhrn", models.CharField(max_length=100)),
                ("nhrn_prod", models.CharField(max_length=100)),
                ("batch_id_expected", models.CharField(max_length=100)),
                ("expiry_date_readed", models.DateField()),
                ("expiry_date_readed_date", models.DateField()),
                ("expiry_date_expected", models.DateField()),
                ("expiry_date_expected_date", models.DateField()),
                ("subuser_id", models.CharField(max_length=100)),
                ("organisation_type", models.CharField(max_length=100)),
                ("initial_decommission_process", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StatusDescription",
            fields=[
                (
                    "status_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages_user_mah", models.TextField()),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("mah_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="sales.alert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.CharField(max_length=20)),
                ("creation_datetime", models.DateTimeField()),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="sales.alert",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
