# Generated by Django 5.0.7 on 2024-08-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alert_statusdescription_interaction_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="status_code",
            new_name="StatusName",
        ),
        migrations.RenameField(
            model_name="statusdescription",
            old_name="status_code",
            new_name="StatusName",
        ),
    ]
