# Generated by Django 5.0.7 on 2024-08-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_rename_status_code_status_statusname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="StatusName",
        ),
        migrations.RemoveField(
            model_name="status",
            name="alert",
        ),
        migrations.RemoveField(
            model_name="status",
            name="creation_datetime",
        ),
        migrations.AddField(
            model_name="alert",
            name="statutName",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")],
                default="Open",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="statutName",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")],
                default="Open",
                max_length=50,
            ),
        ),
    ]
