# Generated by Django 5.0.7 on 2024-08-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_status_statusname_remove_status_alert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmsAlertsInteractions",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("messages_user_mah", models.TextField(null=True)),
                ("CreationDatetime", models.DateTimeField()),
                ("MAHId", models.CharField(max_length=200, null=True)),
                ("UserId", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AmsAlertsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StatusCode", models.CharField(max_length=100)),
                ("CreationDatetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AmsListStatus",
            fields=[
                (
                    "StatusCode",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("StatusName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DwhNMVSFctAlertsL5",
            fields=[
                (
                    "AlertId",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("TransactionTime", models.DateTimeField()),
                ("ProductCode", models.CharField(max_length=100)),
                ("ExceptionLevel", models.CharField(max_length=100)),
                ("Serialnumber", models.CharField(max_length=100)),
                ("ClientId", models.CharField(max_length=100)),
                ("UserId", models.CharField(max_length=100)),
                ("MAHName", models.CharField(max_length=100)),
                ("BatchIdReaded", models.CharField(max_length=100)),
                ("ReturnCode", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="alert",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.DeleteModel(
            name="StatusDescription",
        ),
        migrations.AddField(
            model_name="amsalertsstatus",
            name="AlertId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.dwhnmvsfctalertsl5",
            ),
        ),
        migrations.AddField(
            model_name="amsalertsinteractions",
            name="AlertId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.dwhnmvsfctalertsl5",
            ),
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="Interaction",
        ),
    ]
