# Generated by Django 5.0.7 on 2024-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_amsalertsinteractions_amsalertsstatus_amsliststatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amsalertsinteractions",
            name="AlertId",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="amsalertsinteractions",
            name="CreationDatetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="amsalertsstatus",
            name="AlertId",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="amsalertsstatus",
            name="StatusCode",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="amsliststatus",
            name="StatusCode",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="amsliststatus",
            name="StatusName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="BatchIdReaded",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ClientId",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ExceptionLevel",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="MAHName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ProductCode",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ReturnCode",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="Serialnumber",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="UserId",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="amsalertsstatus",
            unique_together={("AlertId", "CreationDatetime")},
        ),
    ]
