# Generated by Django 5.0.7 on 2024-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_amsalertsinteractions_alertid_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="amsalertsstatus",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="amsalertsinteractions",
            name="MAHId",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="amsalertsinteractions",
            name="UserId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="amsalertsinteractions",
            name="messages_user_mah",
            field=models.TextField(default="No message"),
        ),
        migrations.AlterField(
            model_name="amsalertsstatus",
            name="StatusCode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="amsliststatus",
            name="StatusCode",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="amsliststatus",
            name="StatusName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="BatchIdReaded",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ClientId",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ExceptionLevel",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="MAHName",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ProductCode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="ReturnCode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="Serialnumber",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dwhnmvsfctalertsl5",
            name="UserId",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="amsalertsinteractions",
            table="Ams_Alerts_Interactions",
        ),
        migrations.AlterModelTable(
            name="amsalertsstatus",
            table="Ams_Alerts_Status",
        ),
        migrations.AlterModelTable(
            name="amsliststatus",
            table="Ams_List_Status",
        ),
        migrations.AlterModelTable(
            name="dwhnmvsfctalertsl5",
            table="Dwh_NMVS_Fct_Alerts_L5",
        ),
    ]
