# Generated by Django 5.0.7 on 2024-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_amsalertsstatus_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ams_Alerts_Interactions",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("AlertId", models.CharField(max_length=300)),
                ("messages_user_mah", models.TextField(null=True)),
                ("CreationDatetime", models.DateTimeField(auto_now_add=True)),
                ("MAHId", models.CharField(max_length=200, null=True)),
                ("UserId", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ams_Alerts_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AlertId", models.CharField(max_length=300)),
                ("StatusCode", models.CharField(max_length=10)),
                ("CreationDatetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ams_List_Status",
            fields=[
                (
                    "StatusCode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("StatusName", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="AmsAlertsInteractions",
        ),
        migrations.DeleteModel(
            name="AmsAlertsStatus",
        ),
        migrations.DeleteModel(
            name="AmsListStatus",
        ),
        migrations.DeleteModel(
            name="DwhNMVSFctAlertsL5",
        ),
    ]
