# Generated by Django 5.0.7 on 2024-08-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_ams_alerts_interactions_ams_alerts_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ams_Alerts_Interactions",
        ),
        migrations.DeleteModel(
            name="Ams_Alerts_Status",
        ),
        migrations.DeleteModel(
            name="Ams_List_Status",
        ),
    ]
