# Generated by Django 5.0.7 on 2024-08-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0009_delete_ams_alerts_interactions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmsAlertsInteractions",
            fields=[
                (
                    "ID",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("AlertId", models.CharField(db_column="AlertId", max_length=300)),
                (
                    "messages_user_mah",
                    models.TextField(db_column="messages_user_mah", null=True),
                ),
                (
                    "CreationDatetime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="CreationDatetime"
                    ),
                ),
                (
                    "MAHId",
                    models.CharField(db_column="MAHId", max_length=200, null=True),
                ),
                (
                    "UserId",
                    models.CharField(db_column="UserId", max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "Ams_Alerts_Interactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AmsAlertsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AlertId", models.CharField(db_column="AlertId", max_length=300)),
                ("StatusCode", models.CharField(db_column="StatusCode", max_length=10)),
                (
                    "CreationDatetime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="CreationDatetime"
                    ),
                ),
            ],
            options={
                "db_table": "Ams_Alerts_Status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AmsListStatus",
            fields=[
                (
                    "StatusCode",
                    models.CharField(
                        db_column="StatusCode",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "StatusName",
                    models.CharField(db_column="StatusName", max_length=100),
                ),
            ],
            options={
                "db_table": "Ams_List_Status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BulkMessageInteraction",
            fields=[
                (
                    "ID",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("AlertId", models.CharField(db_column="AlertId", max_length=300)),
                ("messages_user_mah", models.TextField(db_column="messages_user_mah")),
                (
                    "CreationDatetime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="CreationDatetime"
                    ),
                ),
                (
                    "MAHId",
                    models.CharField(db_column="MAHId", max_length=200, null=True),
                ),
                (
                    "UserId",
                    models.CharField(db_column="UserId", max_length=100, null=True),
                ),
                ("AlertIdBulkId", models.IntegerField(db_column="AlertIdBulkId")),
            ],
            options={
                "db_table": "Ams_Alerts_Interactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BulkStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AlertId", models.CharField(db_column="AlertId", max_length=300)),
                ("StatusCode", models.CharField(db_column="StatusCode", max_length=10)),
                (
                    "CreationDatetime",
                    models.DateTimeField(
                        auto_now_add=True, db_column="CreationDatetime"
                    ),
                ),
                ("AlertIdBulkId", models.IntegerField(db_column="AlertIdBulkId")),
            ],
            options={
                "db_table": "Ams_Alerts_Status",
                "managed": False,
            },
        ),
    ]
